prometheus:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressClassName: "traefik"
    hosts:
      - "monitor.feralwolf.ir"
    paths:
      - /
    tls:
      - hosts:
          - "monitor.feralwolf.ir"
        secretName: "monitor-argocd-secret"
    servicePort: 80
  prometheusSpec:
    routePrefix: /
  service:
    port: 80
