prometheus:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressClassName: "traefik"
    hosts:
      - "prometheus.feralwolf.ir"
    paths:
      - /
    tls:
      - hosts:
          - "prometheus.feralwolf.ir"
        secretName: "feral-prometheus-secret"
    status:
      loadBalancer:
        ingress:
          - hostname: prometheus.feralwolf.ir
    servicePort: 80
 

grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressClassName: "traefik"
    hosts:
      - "monitor.feralwolf.ir"
    paths:
      - /
    tls:
      - hosts:
          - "monitor.feralwolf.ir"
        secretName: "feral-grafana-secret"
    status:
      loadBalancer:
        ingress:
          - hostname: monitor.feralwolf.ir
    servicePort: 80
    
